Repository alkemyTech/OT130-CLIENT, pull requests merged in 2022-03, with the labels that each got.

#97 Ot130 120 leer los terminos y condiciones de la ong
  package.json
  public/assets/docs/test.pdf
  src/App.css
  src/Components/Auth/RegisterForm.js
  src/Components/Modal/TermsAndConditionModal.js
  src/Components/Modal/index.css
  src/Components/RenderPdf/ControlPanel.js
  src/Components/RenderPdf/PDFConfig.js
  src/Components/RenderPdf/PDFReader.js
  src/Helpers/formValidations.js
  src/Helpers/messagesText.js
  src/actions/termsAndConditionsActions.js
  src/actions/usersActions.js
  src/app/store.js
  src/index.js
  src/reducers/novedadesReducer.js
  src/reducers/termsAndConditionsReducer.js
  src/reducers/usersReducer.js
  src/rutas/Public.js
  src/rutas/config.js
  src/staticFiles/pdfs.js
Labels: enhancement

#120 Ot130 141 proteccion de rutas de administrador
  src/Components/Auth/ProtectedBackOfficeRoute.js
  src/rutas/Backoffice.js
Labels: enhancement

#125 Fix/errores en HomeForm
  .env.example
  src/Components/HomeForm/HomeForm.js
  src/Services/organizationService.js
  src/Services/slidesService.js
Labels: bug

#126 Fix/ActivitiesList estaba incompleto
  src/Components/Activities/ActivitiesList.js
  src/Components/Activities/ActivityItem.js
  src/Components/Activities/BackofficeActivitiesList.js
Labels: bug, enhancement

#123 Ot130 124 crear componente header para web publica
  src/Campaigns/School/SchoolCampaign.js
  src/Components/Header/Header.js
  src/Components/Header/header.css
  src/config/colorConfig.js
  src/rutas/Public.js
  src/rutas/config.js
Labels: enhancement

#119 Ot130 134 estructurar componente header
  src/Campaigns/Shared/HeaderCampaigns.js
  src/Campaigns/Shared/headerCampaign.css
  src/Campaigns/Toys/Header.js
  src/Campaigns/Toys/ToysCampaign.js
  src/Campaigns/config/campaignConfig.js
  src/assets/index.js
  src/assets/logoJuguetes.png
  src/assets/logoVueltaAlCole.png
Labels: enhancement

#118 Ot 130 127 crear layout para renderizar el contenido de las rutas de backoffice
  src/App.js
  src/Backoffice/Header.js
  src/Backoffice/SideBar/SideBar.css
  src/Backoffice/SideBar/SideBarLink.js
  src/Backoffice/SideBar/index.js
  src/Backoffice/dashboard/CardBackoffice.js
  src/Backoffice/dashboard/CardsBackoffice.js
  src/Backoffice/dashboard/cardBackoffice.css
  src/Backoffice/index.js
  src/Components/Header/Header.js
  src/Screens/Organization/Organization.js
  src/Screens/Organization/OrganizationEdit.js
  src/routes/BackofficeRoutes.js
  src/routes/Public.js
  src/routes/config.js
  src/rutas/Backoffice.js
Labels: enhancement

#90 OT130-128 Integrar header y footer en web pública
  src/App.js
  src/Components/Layout/Layout.js
  src/routes/Public.js
Labels: enhancement

#132 OT-130-ISSUE-#129-Cannot-find-file-index.js-in-src-Components-Home-Index.js
  src/routes/Public.js
Labels: bug

#133 se cambio icono y titulo de pestaña
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
Labels: enhancement

#135 correcion de variable organization en footer de layout principal
  src/Components/Footer/Footer.js
Labels: bug

#88 OT130-139 Proteger rutas de acceso privado
  src/Components/Auth/ProtectedBackOfficeRoute.js
  src/Components/Auth/ProtectedRoute.js
  src/routes/BackofficeRoutes.js
  src/routes/Public.js
Labels: enhancement

#106 OT-130-140-Crear logica de cierre de sesión
  .env.example
  src/App.css
  src/App.js
  src/Backoffice/Header.js
  src/Backoffice/SideBar/index.js
  src/Components/Auth/LoginForm.js
  src/Components/Auth/Logout.js
  src/Components/Auth/RegisterForm.js
  src/Components/Header/Header.js
  src/Components/Header/header.css
  src/Components/SideBar/SideBar.css
  src/Components/SideBar/SideBarLink.js
  src/Components/SideBar/index.js
  src/Services/privateApiService.js
  src/Services/publicApiService.js
  src/reducers/auth/authReducer.js
  src/reducers/auth/constants.js
  src/routes/Public.js
Labels: enhancement

#138 Ot130 137 estructurar componente slider
  src/Campaigns/School/SchoolCampaign.js
  src/Components/Carousel/Carousel.css
  src/Components/Carousel/Carousel.js
  src/Services/mocks/schoolSliders.json
Labels: enhancement

#111 OT130-142 mostrando el boton de donaciones solamente a los usuarios standart
  package.json
  src/Components/Header/Header.js
  src/Components/Home/Index.js
  src/Components/Users/UsersForm.js
  src/Helpers/userTypes.js
Labels: enhancement

#141 Feature/countdown dinámico
  src/Campaigns/School/Content.js
  src/Campaigns/Toys/Content/Content.js
  src/Components/Countdown/Countdown.js
  src/Helpers/daysUntilDate.js
Labels: enhancement

#142 Agregado un hardcodeo para hacer usuario admin. Y cosas que fui encontrando
  src/Components/Activities/index.js
  src/Components/Auth/LoginForm.js
  src/Components/Auth/ProtectedRoute.js
  src/Components/Auth/RegisterForm.js
  src/Screens/Activities/ActivitiesEdition.js
Labels: bug

#152 Fix Header duplicado en landing
  src/Components/Home/Index.js
Labels: bug

#137 Ot 130 issue #136 renderización erronea de footers en pages contacto y campañas
  src/App.js
  src/Campaigns/School/SchoolCampaign.js
  src/Campaigns/Shared/FooterCampaings.js
  src/Campaigns/Shared/HeaderCampaigns.js
  src/Campaigns/Toys/ToysCampaign.js
  src/Campaigns/index.js
  src/Components/Contact/index.js
  src/Components/Footer/Footer.js
  src/Components/Home/Index.js
  src/Components/Layout/Layout.js
  src/Components/Members/MembersForm.js
  src/Components/Testimonials/TestimonialsForm.js
  src/Helpers/daysUntilDate.js
  src/routes/CampaignsRoutes.js
  src/routes/Public.js
  src/routes/config.js
Labels: enhancement

#163 Arreglados carousels de campañas
  src/Campaigns/School/SchoolCampaign.js
  src/Campaigns/Toys/ToysCampaign.js
  src/Components/Carousel/Carousel.js
Labels: bug

#166 0 t130 issue#144 texto de bienvenida de la web publica y Imagenes en el slide de escuela.
  src/App.css
  src/Components/Carousel/Carousel.css
  src/Components/Home/CarouselHero.js
  src/Components/Home/Hero.css
  src/Services/mocks/schoolSliders.json
Labels: bug

#155 adding search form activities
  src/Components/Activities/ActivitiesList.js
  src/Components/Activities/ActivityItem.js
  src/Components/Activities/ActivitySearchForm.css
  src/Components/Activities/ActivitySearchForm.js
  src/Components/Activities/BackofficeActivitiesList.js
  src/Screens/Activities/ActivitiesEdition.js
Labels: enhancement

#122 Ot130 165 crear formulario de busqueda de novedades (backoffice)
  package.json
  src/Components/News/News.js
  src/Components/News/NewsCard.js
  src/Components/News/NewsList.js
  src/Components/NewsSearchForm/NewsSearchForm.js
  src/Components/Skeleton/Skeleton.js
  src/Services/newsService.js
  src/actions/novedadesActions.js
  src/reducers/novedadesReducer.js
Labels: enhancement
