Repository alkemyTech/OT130-CLIENT, pull requests merged in 2022-02, with the labels that each got.

#4 Ot130 33 formulario creación edición usuarios
  src/App.js
  src/Components/Users/CreateEditUser.js
  src/Components/Users/UsersForm.js
  src/Helpers/formValidations.js
  src/Helpers/messagesText.js
  src/Helpers/userTypes.js
  src/Services/usersService.js
  src/config/imageConfig.js
Labels: enhancement

#7 Ot130 32 formulario edición home
  package.json
  src/App.js
  src/Components/HomeForm/HomeForm.js
  src/Components/WelcomeTextForm/WelcomeTextForm.js
  src/Services/organizationService.js
  src/Services/slidesService.js
Labels: enhancement

#36 Implementación Alertas
  package.json
  src/Components/Alert/index.js
  src/Helpers/constants.js
Labels: enhancement

#15 Ot130 29 Create edit activity form
  src/App.js
  src/Components/Activities/ActivitiesForm.js
  src/Components/EmptyScreen/index.js
  src/Components/EmptyScreen/styles.css
  src/Helpers/base64.js
  src/Helpers/messagesText.js
  src/Screens/Activities/ActivitiesCreation.js
  src/Screens/Activities/ActivitiesEdition.js
  src/Screens/Activities/styles.css
  src/Services/activitiesService.js
  src/Services/config.js
  src/Services/privateApiService.js
  src/rutas/config.js
Labels: enhancement

#47 Ot130 34 formulario de actualizacion de datos de organizacion
  src/App.js
  src/Components/Organization/OrganizationEditForm.js
  src/Screens/Organization/OrganizationEdit.js
  src/Services/organizationService.js
Labels: enhancement

#50 Fixed post on Get method
  src/Services/privateApiService.js
Labels: bug, enhancement

#10 Ot130 30 formulario edicion creacion de slides
  src/Components/FormStyles.css
  src/Components/Slides/SlidesForm.js
  src/Services/slidesService.js
Labels: enhancement

#21 Ot130 54 crear componente para renderizar seccion nosotros con informacion de la ong
  src/App.js
  src/Components/About/About.js
  src/Components/ListTexts/ListTexts.css
  src/Components/ListTexts/ListTexts.js
  src/Services/aboutService.js
  src/Services/mocks/about.json
Labels: enhancement

#24 OT130-59 Crear componente donación y gracias
  src/App.js
  src/Components/Donations/Donation.css
  src/Components/Donations/Donation.js
  src/Components/Donations/DonationButton.js
  src/Components/Donations/Thanks.js
  src/Helpers/messagesText.js
Labels: enhancement

#26 OT130-50 creacion componente detail
  src/App.js
  src/Components/Activities/Detail/ActivityDetail.css
  src/Components/Activities/Detail/ActivityDetail.js
Labels: enhancement

#17 Ot130 52/componente y estructura renderizado inicio
  package.json
  src/App.js
  src/Components/Home/CarouselHero.js
  src/Components/Home/Hero.css
  src/Components/Home/Index.js
  src/Components/Home/News.css
  src/Components/Home/News.js
  src/Services/publicApiService.js
Labels: enhancement

#33 OT130-58-Crear-componente-contenido-de-actividad
  src/Components/Activities/ActivitiesContent.js
Labels: enhancement

#23 Ot130 57 Componente para reenderizar sección actividades
  package.json
  src/App.js
  src/Components/Activities/ActivitiesList.js
  src/Components/Activities/index.js
  src/Components/Home/Index.js
  src/Components/Users/UsersForm.js
  src/Helpers/messagesText.js
  src/Helpers/userTypes.js
  src/Services/activitiesService.js
  src/Services/mocks/activities.json
  src/Services/publicApiService.js
  src/customHooks/useRequestActivities.js
  src/rutas/config.js
Labels: enhancement

#5 Ot130 39 backoffice organization screen
  src/App.js
  src/Components/Organization/styles.css
  src/Helpers/messagesText.js
  src/Screens/Organization/Organization.js
  src/Screens/Organization/styles.css
  src/Services/config.js
  src/Services/organizationService.js
  src/assets/index.js
  src/assets/logo.png
  src/rutas/config.js
Labels: enhancement

#32 Ot130 67 componente listado de miembros de org para página nosotros
  package.json
  src/Components/About/MembersList.js
  src/Components/CardListStyles.css
  src/Services/membersService.js
  src/Services/mocks/members.json
  src/customHooks/useRequestMembers.js
Labels: enhancement

#22 Ot130 64 screen listado de slides
  src/App.js
  src/Components/SlideCard/SlideCard.css
  src/Components/SlideCard/SlideCard.js
  src/Components/Slides/SlidesList.js
  src/Services/privateApiService.js
  src/Services/slidesService.js
Labels: enhancement

#57 OT130-60 Componente Card para mostrar en listados
  src/Components/Card/index.js
  src/Components/Card/styles.css
  src/Helpers/messagesText.js
Labels: enhancement

#54 OT-130-95-Setup-Alertas
  src/Components/Alert/index.js
  src/Helpers/messagesText.js
Labels: enhancement

#61 Actualiza librería de alertas
  src/Components/HomeForm/HomeForm.js
  src/Components/WelcomeTextForm/WelcomeTextForm.js
Labels: enhancement

#51 OT130-69 implementing method getToken and getAuthorization
  src/Services/privateApiService.js
Labels: enhancement

#65 Ot130 65 backoffice screen listado de usuarios
  package.json
  src/App.js
  src/Components/Alert/index.js
  src/Components/Users/CreateEditUser.js
  src/Components/Users/UserList.js
  src/Services/privateApiService.js
  src/Services/usersService.js
Labels: enhancement

#75 Ot130 68 crear metodo petición get a los endpoints privados de la api
  src/Services/privateApiService.js
Labels: enhancement

#30 OT130-74 Método GET reutilizable rutas públicas API
  src/Services/publicApiService.js
Labels: enhancement

#39 OT130-72 peticion patch reutilizable
  src/Services/privateApiService.js
Labels: enhancement

#41 OT130-77-Extender-el-servicio-HTTP-base-para-las-peticiones-de-Actividades
  src/Services/activitiesService.js
Labels: enhancement

#86 Ot130 85 crea variables de entorno para endpoint de novedades
  .env.example
  src/Services/homeService.js
  src/Services/newsService.js
Labels: enhancement

#79 Ot130 88 crear variables de entorno
  src/.env.example
  src/Services/contactsService.js
  src/Services/privateApiService.js
Labels: enhancement

#58 OT130-86 Variables de entorno categories
  .env.example
  src/Services/categoriesService.js
Labels: enhancement

#72 Ot130 93 setup skeleton
  README.md
  src/Components/Skeleton/Skeleton.css
  src/Components/Skeleton/Skeleton.js
Labels: enhancement

#68 Ot130 94 setup progress
  README.md
  src/Components/Progress/Progress.css
  src/Components/Progress/Progress.js
Labels: documentation, enhancement

#44 OT130-71 Metodo PUT reutilizable
  src/Services/privateApiService.js
Labels: enhancement

#78 OT130-87-Crear-variables-de-entorno
  .env.example
  src/Services/membersService.js
Labels: enhancement

#87 Ot 130 103 mostrar errores de peticiones contacto
  src/App.js
  src/Components/Contact/ContactForm.js
  src/Components/Contact/ContactsList.js
  src/Components/Contact/index.js
  src/Services/contactsService.js
  src/customHooks/useRequestContacts.js
Labels: enhancement

#66 Ot130 91 creacion variable de entorno
  src/App.js
  src/Services/organizationService.js
  src/Services/privateApiService.js
Labels: enhancement

#76 Ot130 110 crear reducer de slides
  src/App.js
  src/Components/Alert/index.js
  src/Components/Slides/SlidesList.js
  src/actions/slidesActions.js
  src/app/store.js
  src/features/counter/Counter.js
  src/features/counter/Counter.module.css
  src/features/counter/counterSlice.js
  src/reducers/slidesSlice.js
Labels: enhancement

#89 Ot130 102 agregando alertas de error al servicio de novedades
  src/Components/News/NewsForm.js
  src/Services/activitiesService.js
Labels: enhancement

#74 OT130-108 Crear Reducer Actividades
  src/Components/Activities/ActivitiesList.js
  src/Components/CardListStyles.css
  src/Services/activitiesService.js
  src/actions/activitiesActions.js
  src/app/store.js
  src/reducers/activitiesReducer.js
Labels: enhancement

#101 Fixed double import
  src/Components/Activities/ActivitiesList.js
Labels: bug

#104 Fix/errores en backoffice activities
  src/App.js
  src/Components/Activities/ActivitiesForm.js
  src/Components/Activities/ActivityItem.js
  src/Components/Activities/BackofficeActivitiesList.js
  src/Components/Activities/BackoficeActivitiesList.js
  src/Screens/Activities/ActivitiesEdition.js
  src/Services/activitiesService.js
Labels: bug

#84 OT130-112-Crear-reducer-de-miembros
  src/Components/Activities/ActivitiesList.js
  src/actions/membersAction.js
  src/app/store.js
  src/reducers/membersReducer.js
Labels: enhancement

#81 OT130-121 Transiciones de navegación
  package.json
  src/App.js
  src/config/transitions.js
Labels: enhancement

#95 Ot 130 115 integrar leaflet maps en screen contacto
  package.json
  src/Components/Contact/index.js
  src/Components/Contact/leafletMap/LeafletMap.js
  src/Components/Contact/leafletMap/UserLocationMarker.js
  src/Components/Contact/leafletMap/iconMarker/GetIconMarker.js
  src/Components/Contact/leafletMap/iconMarker/icon_marker_location.png
  src/Components/Contact/leafletMap/leafletMap.css
  src/assets/index.js
Labels: enhancement

#94 Ot130 107 reducer de novedades
  src/Components/News/NewsForm.js
  src/Services/activitiesService.js
  src/actions/novedadesActions.js
  src/app/store.js
  src/reducers/novedadesReducer.js
Labels: enhancement

#115 Fix errores de NewsForm y novedadesReducer
  src/Components/News/NewsForm.js
  src/reducers/novedadesReducer.js
Labels: bug

#117 OT130-114 Modularizar router para disponer de ruteo público y admin
  src/App.js
  src/rutas/Backoffice.js
  src/rutas/Public.js
Labels: enhancement

#108 OT130-132 estructurar componente contenido escolar
  public/images/schools_content.png
  public/images/schools_content1.png
  src/Campaigns/School/Content.css
  src/Campaigns/School/Content.js
  src/Helpers/daysUntilDate.js
  src/Helpers/messagesText.js
Labels: enhancement
